var a=10;
document.write("Result:<br> The Value of a is: "+a+"<br><hr>")
document.write("<br><br> The Value of ++a is: "+ ++a)
document.write("<br> Now the Value of a is: "+a)
document.write("<br><br> The Value of a++ is: "+ a++)
document.write("<br> Now the Value of a is: "+a)
document.write("<br><br> The Value of --a is: "+ --a)
document.write("<br> Now the Value of a is: "+a)
document.write("<br><br> The Value of a-- is: "+ a--)
document.write("<br> Now the Value of a is: "+a)